testing: testing.par
	cd ../../jscc; java -jar /usr/share/java/js.jar jscc.js ../shomp/parser/testing.par -o ../shomp/parser/testing.js

min: min.par
	cd ../../jscc; java -jar /usr/share/java/js.jar jscc.js ../shomp/parser/min.par -o ../shomp/parser/min.js
